### ISSUE TITLE
a question about jspatcher installation

### ISSUE THREAD

**Issue by slemouton** [Fr0stbyteR/jspatcher#11]
I have seen your brilliant presentation at the WAC 2021 : bravo, it is an truly remarkable project !
I have a question : what is the simplest way to deploy jspatcher on a local server ?
Thanks in advance for any advice.

**Comment by Fr0stbyteR** [comment]
Hi, thank you for your kind words. 
If you already have a local server, you can just serve the repository folder and open the `dist/index.html`.
If not, you can try `SimpleHTTPServer` with Python. There are many tutorials that can be found easily.
Please note that it's better to add the following header to the HTML file to enable in Chrome the `SharedArrayBuffer` API that is used in some JSPatcher features.

```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

I'll try to add a simple server to the repo in the future!

**Comment by slemouton** [comment]
Hi,
It works ! Thanks a lot
