### ISSUE TITLE
Running the app in Chrome

### ISSUE THREAD

**Issue by freeeco** [Fr0stbyteR/jspatcher#6]
Hi Ren, Just saw this on the PAW 2020 Live Stream, looks great!

I'm trying to run it in Chrome on macOS Catalina, but I just get a black screen when I open: 

/jspatcher-master/dist/index.html

Any idea what I'm doing wrong?

David

**Comment by Fr0stbyteR** [comment]
Hi David,

you can try out the PAW examples online with this link: https://fr0stbyter.github.io/jspatcher/dist/?projectZip=../examples/paw.zip
then if you switch to this link https://fr0stbyter.github.io/jspatcher/dist/
you can add or modify files in the project as you wish.
It is a Progressive Web App so you can simply install the App by clicking the + button on the address bar. With this link it will keep updated to the most recent version, so I recommend this way.
If you wish to run a local copy of the project, you'll need to setup a local server against the project directory. One simple way to do that is using a Chrome plugin: [Chrome Web Server](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb)

**Comment by freeeco** [comment]
Brilliant, thanks!
